import Head from 'next/head'

import AppBar from "../Component/AppBar/index"
import Header from '@/Component/Global/Header'
import Hero from '@/Component/Hero/Hero'
import Image from 'next/image'
import Card from "../Component/Cards/Cards"
import UseProduct from '@/Component/UseProduct/UseProduct'
import Investor from '@/Component/Investors/Investor'
import CMT from '@/Component/CMT/CMT'
import Review from '@/Component/Review/Review'
import Ecosystem from '@/Component/Ecosystem/Ecosystem'
import Media from '@/Component/Media/Media'
import JoinUs from '@/Component/JoinUs/JoinUs'
import Footer from '@/Component/Global/Footer'
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <AppBar /> */}
      <div className='relative h-[100vh]'>
        <Header />
        <Hero />
        <div className='max-h-[968px] max-w-[868px] z-[-99] absolute top-0 right-0'>
          <Image src={"/right.svg"} height={968} width={968} />
        </div>
        <div className='max-h-[230px] max-w-[230px] z-[-99] absolute top-[64px] left-0'>
          <Image src={"/left.svg"} height={230} width={230} />
        </div>

        <div className='max-h-[248px] max-w-[248px] z-[-99] absolute bottom-0 left-0'>
          <Image src={"/bottom.svg"} height={248} width={248} />
        </div>
      </div>
      <Card />
      <UseProduct />
      <Investor />
      <CMT />
      <Review />
      <Ecosystem />
      <Media />
      <JoinUs />
      <Footer />
    </>
  )
}
